### ISSUE TITLE
elyra notebook does not start

### ISSUE THREAD

**Issue by goern** [mamurak/os-mlops#2]
I am following `odh-kfp-modelmesh.md`, and step 'Set up Elyra notebook' askes me to verify/start an Elyra KFNBC

the pod log (among others) gives me:
```
ERROR: Parameter '--cos_endpoint' requires a value.
```

**Comment by goern** [comment]
the elyra notebook does also not show on odh-dashboard
![image](https://user-images.githubusercontent.com/260331/223734258-0979cfd7-499e-4eb6-84d4-03bdb5237722.png)

**Comment by mamurak** [comment]
Thanks for the heads up @goern. The documentation referenced an outdated elyra notebook. I've updated the reference. Can you please try again?

**Comment by goern** [comment]
works! thx!
/close
